---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: requeueip-admin
rules:
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautoippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautoippools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautoips
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautosubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautosubnets/status
  verbs:
  - get
  - patch
  - update
