// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 The RequeueIP Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sauto4/requeueip/openapi/v1/ipam/models"
)

// DeleteIpamIpsOKCode is the HTTP code returned for type DeleteIpamIpsOK
const DeleteIpamIpsOKCode int = 200

/*
DeleteIpamIpsOK Success

swagger:response deleteIpamIpsOK
*/
type DeleteIpamIpsOK struct {
}

// NewDeleteIpamIpsOK creates DeleteIpamIpsOK with default headers values
func NewDeleteIpamIpsOK() *DeleteIpamIpsOK {

	return &DeleteIpamIpsOK{}
}

// WriteResponse to the client
func (o *DeleteIpamIpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteIpamIpsInternalServerErrorCode is the HTTP code returned for type DeleteIpamIpsInternalServerError
const DeleteIpamIpsInternalServerErrorCode int = 500

/*
DeleteIpamIpsInternalServerError Failed to release IP addresses

swagger:response deleteIpamIpsInternalServerError
*/
type DeleteIpamIpsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteIpamIpsInternalServerError creates DeleteIpamIpsInternalServerError with default headers values
func NewDeleteIpamIpsInternalServerError() *DeleteIpamIpsInternalServerError {

	return &DeleteIpamIpsInternalServerError{}
}

// WithPayload adds the payload to the delete ipam ips internal server error response
func (o *DeleteIpamIpsInternalServerError) WithPayload(payload models.Error) *DeleteIpamIpsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ipam ips internal server error response
func (o *DeleteIpamIpsInternalServerError) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteIpamIpsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
