// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 The RequeueIP Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetIpamHealthzReader is a Reader for the GetIpamHealthz structure.
type GetIpamHealthzReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIpamHealthzReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIpamHealthzOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetIpamHealthzOK creates a GetIpamHealthzOK with default headers values
func NewGetIpamHealthzOK() *GetIpamHealthzOK {
	return &GetIpamHealthzOK{}
}

/*
GetIpamHealthzOK describes a response with status code 200, with default header values.

Success
*/
type GetIpamHealthzOK struct {
}

// IsSuccess returns true when this get ipam healthz o k response has a 2xx status code
func (o *GetIpamHealthzOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ipam healthz o k response has a 3xx status code
func (o *GetIpamHealthzOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ipam healthz o k response has a 4xx status code
func (o *GetIpamHealthzOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ipam healthz o k response has a 5xx status code
func (o *GetIpamHealthzOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ipam healthz o k response a status code equal to that given
func (o *GetIpamHealthzOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get ipam healthz o k response
func (o *GetIpamHealthzOK) Code() int {
	return 200
}

func (o *GetIpamHealthzOK) Error() string {
	return fmt.Sprintf("[GET /ipam/healthz][%d] getIpamHealthzOK ", 200)
}

func (o *GetIpamHealthzOK) String() string {
	return fmt.Sprintf("[GET /ipam/healthz][%d] getIpamHealthzOK ", 200)
}

func (o *GetIpamHealthzOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
